cbrnr/mnelab

- mnelab.py
Move data sets into separate classes
> Refactor data

- mnelab.py
I think it makes sense to decouple the data object (previously an attribute `self.all`) from the `MainWindow` object. I guess the easiest solution is to put it in a global `data` object instead.
> Refactor self.all into a global data object

- mnelab/mnelab.py
I'll need to handle `.fif.gz` files, but there are currently [issues with the save dialog](https://bugreports.qt.io/browse/QTBUG-44227).
> Add option to load and export FIF files

- mnelab.py
- mnelab/dialogs/calcdialog.py
- mnelab/dialogs/runicadialog.py
- mnelab/mainwindow.py
- mnelab/utils/datasets.py
I seem to have hit a dead end here. Here's what I want to do: To run ICA, you can click on "Tools" - "Run ICA..." and select some options in the dialog (make sure that you have loaded a dataset before). After confirming with OK, a new dialog pops up, which provides an option to cancel the ongoing computation.
I cannot start `ica.fit()` in the main Python process, because it would block the GUI (which I only need to be able to cancel the calculation). I asked a [question on SO](https://stackoverflow.com/questions/48262966/terminate-a-long-running-python-command-within-a-pyqt-application), and they recommended the multiprocessing module. However, this approach has two drawbacks:
1. It only works for the toy example and not for the real thing in MNELAB (on macOS, I get dozens of these …
> Compute ICA

- README.md
- mnelab/dialogs/pickchannelsdialog.py
- mnelab/mainwindow.py
- mnelab/tests/test_actions.py
- setup.py
Move all actions into `self.actions` dict
> Actions dict

- README.md
- mnelab/__main__.py
- setup.py
This is necessary for creating an executable with setuptools (but this doesn't work yet).
> Change entry point

- mnelab/dialogs/eventsdialog.py
- mnelab/mainwindow.py
Enable editing of events in dialog
> Edit events

- mnelab/dialogs/annotationsdialog.py
- mnelab/mainwindow.py
- mnelab/model.py
Similar to edit events, this PR will add a dialog in which annotations can be edited, added, and removed.
> Edit annotations

- MANIFEST.in
- setup.py
I'm currently in the process of creating a `conda-forge` package of `mnelab`, and they require a license file to be included.
btw, would you like to be listed as a maintainer of the `conda-forge` feedstock?
> PKG: Include license file in sdist

- README.md
> DOC: Urge users to install into dedicated conda env

- CHANGELOG.md
- mnelab/mainwindow.py
Fixes #36. @hoechenberger can you test if this fixes the issue for you?
> Handle files that don't exist in Recent menu

- CHANGELOG.md
- mnelab/mainwindow.py
> Don't crash if not all three BrainVision files are present

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
Fixes #47. @hoechenberger please check if this solves the issue.
> Create events from annotations

- CHANGELOG.md
- mnelab/dialogs/interpolatebadsdialog.py
- mnelab/mainwindow.py
- mnelab/model.py
This PR add the ability to use `.interpolate_bads` on raw, epoch and evoked data
> ADD Interpolate bad Channels

- CHANGELOG.md
- mnelab/dialogs/errormessagebox.py
- mnelab/mainwindow.py
> Fix visual glitch in info widget when showing dialogs

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
> Split export data into submenus

- CHANGELOG.md
- README.md
- mnelab/mainwindow.py
- mnelab/model.py
- mnelab/utils/dependencies.py
Requires [pybv](https://github.com/bids-standard/pybv). Some things are not optimal yet, see https://github.com/bids-standard/pybv/issues/31 and https://github.com/bids-standard/pybv/issues/30, but the basic thing works.
> Add support for exporting to BrainVision

- CHANGELOG.md
- mnelab/model.py
> Correctly report the file size for BrainVision data

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
- mnelab/utils/io.py
Add support for
- Neuroscan CNT
- EGI Netstation MFF
- Nexstim eXimia NXE
> Add more file formats (CNT, MFF, NXE)

- CHANGELOG.md
- mnelab/dialogs/cropdialog.py
- mnelab/mainwindow.py
- mnelab/model.py
> Add crop functionality

- README.md
- requirements.txt
- setup.py
Added to README.md, requirements.txt, and setup.py
> Add pyobjc-framework-Cocoa

- CHANGELOG.md
- mnelab/mainwindow.py
> List package dependencies in About dialog

- CHANGELOG.md
- mnelab/__main__.py
> Fix blurry icons on macOS

- CHANGELOG.md
- LICENSE
- README.md
- mnelab/dialogs/montagedialog.py
- mnelab/mainwindow.py
- mnelab/model.py
- mnelab/utils/dependencies.py
- requirements-oldest.txt
- setup.py
MNE now uses `mne.channels.make_standard_montage` instead of `mne.channels.read_montage`.
> Fix montage

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
- mnelab/utils/io.py
> Add more items to history

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- azure-pipelines.yml
- mnelab/__main__.py
- mnelab/dialogs/annotationsdialog.py
- mnelab/dialogs/calcdialog.py
- mnelab/dialogs/channelpropertiesdialog.py
- mnelab/dialogs/cropdialog.py
- mnelab/dialogs/epochdialog.py
- mnelab/dialogs/errormessagebox.py
- mnelab/dialogs/eventsdialog.py
- mnelab/dialogs/filterdialog.py
- mnelab/dialogs/findeventsdialog.py
- mnelab/dialogs/historydialog.py
- mnelab/dialogs/interpolatebadsdialog.py
- mnelab/dialogs/metainfodialog.py
- mnelab/dialogs/montagedialog.py
- mnelab/dialogs/pickchannelsdialog.py
- mnelab/dialogs/referencedialog.py
- mnelab/dialogs/runicadialog.py
- mnelab/dialogs/xdfstreamsdialog.py
- mnelab/mainwindow.py
- mnelab/resources.py
- mnelab/utils/dependencies.py
- mnelab/widgets/infowidget.py
- requirements-oldest.txt
- requirements.txt
- setup.py
> Replace PyQt5 with QtPy

- CHANGELOG.md
- mnelab/dialogs/__init__.py
- mnelab/dialogs/appenddialog.py
- mnelab/dialogs/concatenatedatadialog.py
- mnelab/mainwindow.py
- mnelab/model.py
> Add option to append data sets

- README.md
- requirements-oldest.txt
- setup.py
This is required for PySide2 support.
> Bump minimum matplotlib version to 2.1.0

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
> Allow to concatenate raws and epochs

- azure-pipelines.yml
Fixes failing Linux jobs on Azure.
> Install more apt packages

- CHANGELOG.md
- MANIFEST.in
Icons were missing when installed via pip, this fixes this issue.
> Add icons to MANIFEST.in

- CHANGELOG.md
- mnelab/dialogs/__init__.py
- mnelab/dialogs/erdsdialog.py
- mnelab/mainwindow.py
- mnelab/viz.py
Fixes #132, closes #164. This is a very basic support for simple ERDS maps which exposes only a few parameters. However, I've hopefully set some sensible defaults so that the maps look OK in most situations. Support for additional settings and fine-tuning can be added in a future PR.
> Add support for basic ERDS maps

- CHANGELOG.md
- mnelab/dialogs/historydialog.py
- mnelab/utils/__init__.py
- mnelab/utils/syntax.py
Makes the history look a lot nicer.
> Add syntax highlighting in history dialog

- azure-pipelines.yml
- mnelab/__init__.py
- mnelab/dialogs/__init__.py
- mnelab/dialogs/historydialog.py
- mnelab/io/writers.py
- mnelab/model.py
All `.py` files should be linted by flake8.
> Try flake8 on CI

- CHANGELOG.md
- mnelab/mainwindow.py
Fixes #165. Also fixes this on other platforms, which might have worked just by chance.
> Fix ICA computation in separate process

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/utils/dependencies.py
Clean up a bit and update About dialog.
> Simplify dependencies

- mnelab/model.py
> Always show a dash for zero events

- CHANGELOG.md
- mnelab/dialogs/annotationsdialog.py
> Fix slow annotations removal

- CHANGELOG.md
- mnelab/dialogs/eventsdialog.py
> Fix slow events dialog

- .github/workflows/python-style.yml
- CONTRIBUTING.md
- mnelab/__main__.py
- mnelab/dialogs/__init__.py
- mnelab/dialogs/annotationsdialog.py
- mnelab/dialogs/appenddialog.py
- mnelab/dialogs/channelpropertiesdialog.py
- mnelab/dialogs/cropdialog.py
- mnelab/dialogs/epochdialog.py
- mnelab/dialogs/erdsdialog.py
- mnelab/dialogs/eventsdialog.py
- mnelab/dialogs/filterdialog.py
- mnelab/dialogs/findeventsdialog.py
- mnelab/dialogs/historydialog.py
- mnelab/dialogs/interpolatebadsdialog.py
- mnelab/dialogs/metainfodialog.py
- mnelab/dialogs/montagedialog.py
- mnelab/dialogs/pickchannelsdialog.py
- mnelab/dialogs/referencedialog.py
- mnelab/dialogs/runicadialog.py
- mnelab/dialogs/xdfstreamsdialog.py
- mnelab/io/readers.py
- mnelab/io/writers.py
- mnelab/mainwindow.py
- mnelab/model.py
- mnelab/viz.py
- mnelab/widgets/infowidget.py
Hopefully everything still works...
> Bump line length to 92 characters

- CHANGELOG.md
- mnelab/io/readers.py
> Use case-insensitive extensions for supported files

- mnelab/mainwindow.py
This was changed in MNE-Python in https://github.com/mne-tools/mne-python/pull/7923
> Use new fNIRS name type

- mnelab/io/readers.py
> Add support for SNIRF files

- MANIFEST.in
- setup.cfg
Remove LICENSE and *.py from MANIFEST.in
> Simplify setup further

- .github/workflows/release.yml
- .github/workflows/test.yml
- CHANGELOG.md
- README.md
- setup.cfg
Remove Python 3.6 and 3.7 and add Python 3.10 support.
> Support Python 3.8, 3.9, and 3.10

- mnelab/io/xdf.py
- mnelab/mainwindow.py
This function is already provided in pyxdf.
> Remove unused get_streams function

- CHANGELOG.md
- mnelab/dialogs/appenddialog.py
> Add move button in Append dialog

- CHANGELOG.md
- CONTRIBUTING.md
- MANIFEST.in
- requirements-dev.txt
- requirements-extras.txt
- requirements.txt
These files are not necessary anymore.
> Remove unnecessary requirements files

- CHANGELOG.md
- mnelab/mainwindow.py
> Enable loading multiple files

- CHANGELOG.md
- mnelab/dialogs/__init__.py
- mnelab/dialogs/plot_evoked.py
- mnelab/mainwindow.py
- mnelab/viz.py
As discussed in #256, this adds a menu entry "Plot evoked...", leading to the following dialog:
If the montage is not set, the topomaps-box is greyed out:
> Add plotting evoked potentials for individual channels

- CHANGELOG.md
- mnelab/dialogs/montage.py
- mnelab/mainwindow.py
- mnelab/model.py
- mnelab/utils/__init__.py
- mnelab/utils/utils.py
This extends the "Set montage..." dialog to allow specifying `match_case`, `match_alias`, and `on_missing` parameters of `set_montage`. Additionally, locations in the infowidget are displayed as (located_channels/all_channels) instead of Yes/No.
> Enhance "Set montage..."

- mnelab/mainwindow.py
> Require Epochs to enable Plot evoked topomaps

- CHANGELOG.md
- mnelab/dialogs/annotations.py
- mnelab/dialogs/events.py
- mnelab/mainwindow.py
- mnelab/model.py
> Enable editing events and annotations when there are none

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
To facilitate reproducing [this tutorial](https://mne.tools/stable/auto_tutorials/evoked/30_eeg_erp.html)
> Allow importing events from FIF files

- CHANGELOG.md
- mnelab/dialogs/__init__.py
- mnelab/dialogs/rename_channels.py
- mnelab/mainwindow.py
- mnelab/model.py
Resolves #298, that's what the dialog looks like:
> Add batch renaming of channels

- mnelab/mainwindow.py
Only the menu changes from #311, the documentation link in "Help" is now part of #281.
> Improve menu

- mnelab/mainwindow.py
> Always enable history

- mnelab/mainwindow.py
> Disable evoked topomaps if no montage is available

- mnelab/dialogs/events.py
This fixes the `KeyError` when removing an event. Fixes #328.
> Fix removing events

- mnelab/dialogs/history.py
> Use platform-specific monospace fonts

- .github/workflows/test.yml
- CHANGELOG.md
- mnelab/model.py
- mnelab/widgets/infowidget.py
When running the dev version, this now prints a red message in the main window to notify users that they are not running the stable version.
> Show dev version

- .github/workflows/release.yml
- .github/workflows/test.yml
Update all actions to their latest versions.
> Bump GitHub actions

- .pre-commit-config.yaml
> Bump pre-commit repos

- .github/workflows/release.yml
- .github/workflows/test.yml
- setup.cfg
Just bumping versions, not changing any code.
> Add Python 3.11 support

- README.md
- setup.cfg
PySide6 6.4.2 fixes incorrect font scaling on Windows.
> Bump PySide6

- .flake8
- .pre-commit-config.yaml
- mnelab/__init__.py
- mnelab/dialogs/channel_properties.py
- mnelab/dialogs/mat.py
- mnelab/dialogs/montage.py
- mnelab/dialogs/pick_channels.py
- mnelab/dialogs/reference.py
- mnelab/dialogs/rename_channels.py
- mnelab/dialogs/xdf_chunks.py
- mnelab/dialogs/xdf_streams.py
- mnelab/io/readers.py
- mnelab/io/writers.py
- mnelab/io/xdf.py
- mnelab/mainwindow.py
- mnelab/model.py
- mnelab/settings.py
- mnelab/utils/utils.py
- mnelab/viz.py
- mnelab/widgets/infowidget.py
- pyproject.toml
Not too many changes, note that we use a line length of 92 characters.
> Reformat with Black

- .flake8
- .pre-commit-config.yaml
- pyproject.toml
Pydocstyle rules could be enabled at a later point.
> Use Ruff and remove Flake8 and isort

- pyproject.toml
See: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
> Set build-system.build-backend in pyproject.toml

- mnelab/mainwindow.py
Here is the tiny change so that ERDS plot can work with newer MNE, as discussed in #381.
> fix ERDS plot with mne >= 1.1.0, fix #381

- .pre-commit-config.yaml
- CONTRIBUTING.md
- pyproject.toml
This should be faster than Black.
> Use Ruff for code formatting

- .github/workflows/release.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- readthedocs.yml
Hopefully, everything should continue to work.
> Update tests to Python 3.12

- CONTRIBUTING.md
- pyproject.toml
After introducing and removing icons using the Qt Resource System, there are a couple of things left that should be removed.
> Remove-icons-cruft

- CHANGELOG.md
- src/mnelab/mainwindow.py
- src/mnelab/settings.py
Added channel settings to options dialog and set default for plotting to 32. Fixes #407.
> Changed default channel settings to 32

- CHANGELOG.md
- README.md
- docs/source/tutorial/index.md
- pyproject.toml
- src/mnelab/io/writers.py
- src/mnelab/utils/dependencies.py
> Make pybv required dependency

- README.md
- docs/source/tutorial/index.md
I don't think it is necessary to list the dependencies here.
> Remove dependencies section

- CONTRIBUTING.md
- pyproject.toml
- src/mnelab/dialogs/channel_properties.py
- src/mnelab/dialogs/events.py
- src/mnelab/dialogs/mat.py
- src/mnelab/dialogs/rename_channels.py
- src/mnelab/io/mat.py
- src/mnelab/io/npy.py
- src/mnelab/io/readers.py
- src/mnelab/io/writers.py
- src/mnelab/io/xdf.py
- src/mnelab/mainwindow.py
- src/mnelab/model.py
- src/mnelab/settings.py
- src/mnelab/utils/utils.py
- src/mnelab/viz.py
- src/mnelab/widgets/infowidget.py
Since Black and Ruff use 88 characters per line as a default, I think it makes sense that we also adopt this value.
> Use max line length of 88

- .github/workflows/release.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- pyproject.toml
- readthedocs.yml
Use `ubuntu-latest` and `ruff-action` instead of via pre-commit.
> Bump runners and use ruff-action

- docs/source/tutorial/index.md
Sync instructions with README.md.
> Update running MNELAB in docs

- .github/workflows/release.yml
I think this should be all since I've already set up trusted publishing on PyPI.
> Use uv for publishing

- .github/workflows/test.yml
If the style check fails, this will show details of all required changes.
> Show diff for ruff format

- CHANGELOG.md
Adding emojis to sections makes it easier to quickly identify the relevant changes.
> Prettify changelog

- CHANGELOG.md
- src/mnelab/mainwindow.py
Fixes [#461](https://github.com/cbrnr/mnelab/issues/461). Hide sidebar when no datasets are loaded.
> Hide sidebar when empty

- CHANGELOG.md
- src/mnelab/dialogs/montage.py
- src/mnelab/mainwindow.py
- src/mnelab/model.py
- src/mnelab/utils/__init__.py
- src/mnelab/utils/utils.py
Fix [#315](https://github.com/cbrnr/mnelab/issues/315). Allow users to select custom montage file in montage dialog
> Custom montage

- CHANGELOG.md
- src/mnelab/dialogs/filter.py
- src/mnelab/mainwindow.py
- src/mnelab/model.py
Fix[ #259](https://github.com/cbrnr/mnelab/issues/259). Extend filter dialog by notch filter and savgol filter options.
> Extend filter dialog

- .github/workflows/test.yml
- CHANGELOG.md
- src/mnelab/__init__.py
- src/mnelab/settings.py
- tests/test_settings.py
The settings location is now shown in the Settings dialog. Also, we need to test reading/writing settings on all three platforms (Windows, macOS, Linux) (this is still to do).
> Improve settings

- src/mnelab/mainwindow.py
- src/mnelab/widgets/sidebar.py
This simplifies the current implementation a bit.
> Move all events to `event` method

- CHANGELOG.md
- src/mnelab/dialogs/__init__.py
- src/mnelab/dialogs/psd.py
- src/mnelab/mainwindow.py
This dialog lets users set the lower and upper frequency bounds, whether to include bad channels (in red) or not, and whether to use spatial colors if a montage is set.
> Add PSD dialog

- pyproject.toml
- tests/test_main.py
Test if the MNELAB main window is created correctly.
> Test main function

- pyproject.toml
- src/mnelab/dialogs/append.py
- src/mnelab/io/writers.py
- src/mnelab/mainwindow.py
- src/mnelab/utils/dependencies.py
- src/mnelab/viz.py
...and fix corresponding code.
> Enable C4 and PERF rules
