cbrnr/mnelab

- mnelab.py
This commit adds logic to the load_file method which checks the extension for
.vhdr, and loads files appropriately.
TODO: Other popular filetypes in [1].
TODO: Allow setting brainvision presets in [2].
[1] http://martinos.org/mne/dev/manual/io.html
[2] http://martinos.org/mne/dev/generated/mne.io.read_raw_brainvision.html#mne.io.read_raw_brainvision
> Allow loading brainvision files.

- mnelab.py
If the user attempts to load a file which is not there, show a critical
QMessageBox with a short message and the full expected filepath.  For example,
this code will run if  a user tries to load a file from the
'Open recent' menu which has been renamed or moved.
If the file doesn't exist, return immediately.
TODO: Log an error here.
> Check if a file exists before trying to load it.

- README.md
- mnelab/dialogs/channelpropertiesdialog.py
- mnelab/dialogs/xdfstreamsdialog.py
- mnelab/mainwindow.py
- mnelab/model.py
- mnelab/utils/__init__.py
- mnelab/utils/dependencies.py
- mnelab/utils/xdf.py
Prepare support for loading XDF files. Currently, XDF can't be loaded yet, but a dialog window shows a list of all available streams contained in the file. Marker streams (streams with fs=0Hz) are disabled. The plan is to load the selected stream (for now, only one stream can be selected and loaded). Marker streams will be imported as annotations.
> [WIP] Support for XDF

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
Fixes #40 @cbrnr & @mmagnuski can you test if if works for you ?
> ADD Apply ICA function

- CHANGELOG.md
- mnelab/dialogs/epochdialog.py
- mnelab/dialogs/epochingdialog.py
- mnelab/mainwindow.py
- mnelab/model.py
- Add an epoching window (to select the events & the length of the interval around the events)
- Add handling of epochs data type (reading and displaying on mnelab)
This is in reference to #42 
There is still a lot to do as I think some functions won't be correctly handing epochs, however it is possible to display the regular plot, the psd_plot, and normally, to compute ICA on epochs.
> [MRG] Add handling of epochs

- CHANGELOG.md
- mnelab/dialogs/historydialog.py
- mnelab/mainwindow.py
Fixes #38. This is a very basic implementation, in a future update line numbers could be added (see https://doc.qt.io/qt-5/qtwidgets-widgets-codeeditor-example.html).
> Add show history dialog

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
Fixes #56. I don't know how to infer changes to bad channels made in the interactive figure window though. Ideas @vferat @mmagnuski @larsoner?
> Add history for changes in channel properties dialog

- CHANGELOG.md
- mnelab/model.py
Instead of removing events present in the raw object used to create epochs, `epochs.events` are now correctly used. Also, the number of epochs is shown for samples (in addition to length).
> Correctly update events for epochs

- CHANGELOG.md
- mnelab/model.py
Requires pybv >= 0.2.0. Furthermore, meas_date is not exported because it creates an additional marker in the .vmrk file (seems a better idea to me, but this can be reverted anytime if people feel it is needed).
> Export annotations duration to BrainVision

- CHANGELOG.md
- mnelab/utils/dependencies.py
This extends the dict by setting the values to the package versions if they exist - if a package does not exist, the value remains `False`, e.g.:
```
{'PyQt5': '5.13.0',
'matplotlib': '3.1.1',
'mne': '0.19.dev0',
'numpy': '1.17.1',
'picard': False,
'pybv': '0.2.0',
'pyedflib': '0.1.14',
'pyxdf': '1.15.2',
'scipy': '1.3.1',
'sklearn': '0.21.3'}
```
> Add version numbers for dependencies (instead of just True/False)

- CHANGELOG.md
- CONTRIBUTING.md
- mnelab/__main__.py
Requires `pyobjc-framework-Cocoa`
> Set app name on macOS

- CHANGELOG.md
- mnelab/mainwindow.py
Previously, only streams with a `nominal_srate` were disabled in the XDF stream selection dialog because we want to treat these as annotations. This PR also disables streams of type string even if these are regularly sampled (we should still treat them as annotations or convert to a numeric type, but this is something for later).
> Disable string streams

- CHANGELOG.md
- CONTRIBUTING.md
- mnelab/mainwindow.py
sdist should work on all platforms because MNELAB is pure Python anyways.
> Remove bdist_wheel because of macOS-only dependency

- README.md
In case people want to stick with the default channel this method also works.
> Add alternative conda installation method

- CHANGELOG.md
- setup.py
`install_requires` can make use of environment markers, so this makes the module a bit shorter.
> Simplify setup.py

- mnelab/utils/io.py
LabRecorder was modified so that the nominal sampling rate is now a string of a double rather than a string of an int. This is actually correct because the type in the lsl::info structure is in fact a double. This means that XDF files recorded with later versions of LabRecorder (unfortunately I couldn't track down the actual commit that made this change) will throw an error at line 232. This small change should prevent this and it should remain back compatible.
> Accomodate changes to LabRecorder nominal srate

- CHANGELOG.md
- README.md
- mnelab/__main__.py
- mnelab/mainwindow.py
- requirements-oldest.txt
- requirements.txt
- setup.py
This PR ensures that we're always running MNELAB with a "framework build" of Python on macOS, if a `conda`-installed Python interpreter is used.
The way this works is the following:
- first, we check whether we're running macOS and in a `conda` environment (upon environment activation, the `CONDA_PREFIX` env variable is set)
- if that's not the case, run the application as usual
- otherwise, spawn a new `pythonw` process (i.e., a framework build) to execute `__main__.py` again, preserving all command line arguments that were initially passed, and set an environment variable `MNELAB_RUNNING_PYTHONW`, indicating we're now using the framework build
- now, when the newly spawned Python interpreter executes `__main__.py`, it will find that we're using a framework build, because the environment …
> ENH: Always run via framework build on macOS conda

- CHANGELOG.md
- mnelab/model.py
MNELAB crashed if the BrainVision data file extension was not `.eeg`. However, the data file name is specified in the `.vhdr` file and can have an arbitrary extension (usually it is either `.eeg` or `.dat`). This PR resolves this issue.
> Correctly load BV files with ext other than .eeg

- CHANGELOG.md
- mnelab/io/writers.py
- mnelab/mainwindow.py
Fix bug that prevented exporting to any file format. Also disable all exporters that don't support epochs for epochs data (currently, only .FIF and .FIF.GZ support epoched data, but I think EEGLAB .SET and BrainVision .EEG should also support that - that's for another PR).
> Correctly enable/disable writers for epochs

- mnelab/dialogs/montagedialog.py
- mnelab/mainwindow.py
Remove status bar from signal plotting and montage plotting. Fixes #161.
> Hide statusbar changed in Matplotlib 3.3

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
Add GUI options to create data annotations from events. Fixes #114.
> Annotations from events

- CHANGELOG.md
- mnelab/model.py
Previously, MNELAB showed an incorrect length in seconds (off by 1 sample). This PR fixes this issue.
> Show correct signal length (in s)

- CHANGELOG.md
- mnelab/model.py
Store event mappings when calling `mne.events_from_annotations` to be able to use them latter on. This commit also considers that event_mappings should be a dictionary of `event_id` and event descriptions with `event_id` as an integer key of a dictionary, and the event description a string. contrary to how they are returned by the `mne.events_from_annotations` function. A fix for this has been implemented by swapping keys and values.
The `event_mappings` is originally swapped because it can be used when [creating epochs](https://mne.tools/stable/generated/mne.Epochs.html#mne.Epochs). If we plan to use the event mappings here I can remove the swap, and implement it only when converting back to annotations. Currently we only use the `mne.Epochs` in a [single …
> Event mappings Fix for #167

- CHANGELOG.md
- azure-pipelines.yml
- requirements-extras.txt
- requirements-oldest.txt
- requirements-optional.txt
- requirements.txt
- setup.py
This PR attempts to simplify package and version requirements. Previously, we had to change versions in two places (`setup.py`, `requirements-oldest.txt`), whereas now there is only one file (`requirements.txt`). The same is true for optional requirements, which are now only contained in `requirements-extras.txt` (and not in `setup.py` anymore).
> Simplify requirements

- CHANGELOG.md
- mnelab/mainwindow.py
This PR should solve issue #176
> Fix export

- CHANGELOG.md
- setup.py
> Add wrapped qt package as dependency fix #182

- CHANGELOG.md
- mnelab/io/readers.py
- mnelab/io/writers.py
- mnelab/mainwindow.py
- mnelab/model.py
This PR fix issues #183 #176
- Concerning #176, ffilter argument removed
- Fix ffilter. Files should now be listed in import/export dialog
- Fix writers/readers extension check to allow dot in file names #183 
- Fix an export .fif crash when the named file exist (managed via QDialogFile)
NB: This just fix export issues but isn't an export refactoring for #178
> Fix export ffilter and extensions

- CHANGELOG.md
- README.md
I've already renamed `master` to `main` on GitHub (https://docs.github.com/en/github/administering-a-repository/renaming-a-branch). This PR replaces all occurrences of `master` with `main`.
> Use main instead of master

- CHANGELOG.md
- setup.py
Previously, checking if `PySide2` or `PyQt5` was installed in conda environments didn't work as expected, because the conda package name `pyqt` is not identical to the module name `PyQt5`. That's why even if `pyqt` was installed, `setup.py` still installed `PyQt5` (from PyPI).
> Fix optional deps for conda

- CHANGELOG.md
- README.md
- requirements-extras.txt
- setup.py
Checking for `PyQt5` or `PySide2` and installing the latter of none is found is rather ad-hoc and doesn't work in many situations. Therefore, I'm removing this feature again and instead will rely on best practices, i.e. users are responsible to install either of these two packages themselves. In addition, `pip install mnelab[pyside2]` and `pip install mnelab[pyqt5]` is now also supported.
> Remove custom setup.py dep check

- CHANGELOG.md
- setup.py
Fixes #153. Basically, I'm replacing`gui_scripts` with `console_scripts`, which works on all supported platforms. This means that the terminal needs to remain open while MNELAB is running. However, this was already the case on Linux and macOS, so it seems like the `gui_scripts` entry point never worked.
> Workaround for mnelab command not working on Windows

- mnelab/mainwindow.py
Sometimes, `self.recent` would contain `None` entries, which caused a warning when showing the recent files menu. Now `self.recent` is cleaned right after loading from settings.
> Fix insert null action

- mnelab/io/xdf.py
Previously it failed at some later stage so this should be a clearer error message.
> Raise IOError if stream_id is not found in XDF file

- CHANGELOG.md
- README.md
- mnelab/__main__.py
Installing with `pip` should also work in `conda` environments. There are still problems with GUI applications using `conda` on macOS, but this should be fixed upstream and not worked around here.
> Remove conda-specific code and instructions

- mnelab/__init__.py
- mnelab/__main__.py
- mnelab/mainwindow.py
- setup.cfg
The `gui_scripts` entry point was broken on Windows. Slightly refactoring the contents of `__init__.py` and `__main__.py` fixes this issue.
> Fix gui_scripts entrypoint

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
Loading XDF requires the `stream_id` argument, and the history for dropping channels was completely wrong.
> Fix history for loading XDF and dropping channels

- CHANGELOG.md
- mnelab/dialogs/xdfstreamsdialog.py
- mnelab/io/xdf.py
- mnelab/mainwindow.py
- mnelab/model.py
By default, the effective sampling rate is used (but this can be changed by unchecking the option in the XDF import dialog).
> Add option to use effective sampling rate for XDF

- CHANGELOG.md
- mnelab/io/xdf.py
When there are two or more marker streams in an XDF file, it is possible that a specific marker type is present in more than one stream. This makes it impossible to disambiguate, for example a marker type `1` could be present in both marker streams with IDs 3 and 5.
This PR adds a `prefix_markers` parameter, which (when `True`) changes the annotation descriptions to `3-1` and `5-1`, respectively.
> Add option to prefix markers in XDF

- CHANGELOG.md
- mnelab/dialogs/xdfstreamsdialog.py
- mnelab/mainwindow.py
- mnelab/model.py
- mnelab/utils/syntax.py
This PR adds a GUI for the new feature introduced with #239.
> Add GUI for prefixing marker streams

- .github/workflows/test.yml
It is probably a good idea to set up Python in the build-wheel job. I'm not even sure why it was working without it before.
> Setup Python in build-wheel job

- CHANGELOG.md
- mnelab/mainwindow.py
Previously, XDF files containing additional dots (e.g. `abc.01.02.xdf`) could not be imported. This PR fixes this.
> Better handle dots in XDF file names

- CHANGELOG.md
- README.md
- mnelab/dialogs/__init__.py
- mnelab/dialogs/xdfchunksdialog.py
- mnelab/io/readers.py
- mnelab/io/xdf.py
- mnelab/mainwindow.py
- mnelab/utils/dependencies.py
- requirements-extras.txt
- setup.cfg
This adds a new dialog window "File–Show XDF chunks...", which lists all chunks contained in an XDF file with some basic information. This also works with corrupted XDF files, so this might be useful to find out what data can be saved from an invalid file.
With this change, `pyxdf` will be a required dependency.
> Add XDF chunk inspection

- CHANGELOG.md
- mnelab/io/readers.py
- mnelab/model.py
Previously, files with more than one dot have not been recognized correctly. This is an extension of #244, which failed to fix `ftype` shown in the MNELAB info widget.
> Improve supported file extension detection

- CHANGELOG.md
- mnelab/io/readers.py
- mnelab/test/test_readers.py
Fixes issue #251.
Previously, loading XDF files with Python 3.8 resulted in an error due to usage of `removesuffix` (Python 3.9+). This PR fixes the problem by using `pathlib.Path.with_suffix`.
> Fix: Split file extension with py38 compatibility

- mnelab/mainwindow.py
When closed, the dialog falls back to "No", so by default a new dataset is created.
Resolves #103
> Make dataset overwrite dialog more explicit

- CHANGELOG.md
- mnelab/dialogs/referencedialog.py
- mnelab/mainwindow.py
- mnelab/model.py
Currently, if the data set does not contain the reference channel, rereferencing requires to open "Set reference..." twice:
- first, to add the reference channel
- second, to actually rereference to the desired channel(s)
Example, following [this](https://github.com/cbrnr/bci_event_2021#erders-analysis-with-mnelab) tutorial:
Here's an idea what the dialog could look like to perform both steps at once (called "Modify reference" to reflect both possible actions):
This could be the initial state:
And only adding a reference channel, without rereferencing would still be possible:
> Enhance "Set reference"

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
I didn't get the `QListView` to allow dropping items only between others, not onto them, so this replaces the sidebar's `QListView` and `QStringListModel` with a `QListWidget`. I'm not sure if this could break something?
The following things work:
- drag and drop reorder (+history)
- data set renaming
@cbrnr, does any missing functionality come to mind?
If not, this fixes #128 :)
> Add drag and drop reordering to sidebar

- CHANGELOG.md
- mnelab/dialogs/meta_info.py
- mnelab/dialogs/xdf_streams.py
- mnelab/mainwindow.py
- As the "Show information..." button is only applicable to XDF files, it is moved to the file menu and renamed to "Show XDF meta information". 
- In the XDF stream selection dialog, a "Details..." button is added which also opens the meta info window.
> Move XDF info to file menu and add XDF streams details button

- CHANGELOG.md
- mnelab/mainwindow.py
As an example, trying to set a montage with channels not in the chosen configuration leads to this ("Show Details..." shows the full traceback):
> Show exceptions in an error message box

- mnelab/io/readers.py
- mnelab/model.py
Resolves #260 
Example screenshot:
This also ensures absolute paths are shown in the infowidget for files loaded via commandline arguments.
> Use short names in sidebar, absolute paths in infowidget

- mnelab/mainwindow.py
If something crashes before the application is able to show the error message box introduced in #268, there's no error message at all. While this should hopefully only happen to developers, it's helpful if all exceptions are also sent to stderr 😅
> Print caught exceptions to stderr

- .pre-commit-config.yaml
- mnelab/__main__.py
- mnelab/dialogs/annotations.py
- mnelab/dialogs/append.py
- mnelab/dialogs/channel_properties.py
- mnelab/dialogs/crop.py
- mnelab/dialogs/epoch.py
- mnelab/dialogs/erds.py
- mnelab/dialogs/events.py
- mnelab/dialogs/filter.py
- mnelab/dialogs/find_events.py
- mnelab/dialogs/history.py
- mnelab/dialogs/interpolate_bads.py
- mnelab/dialogs/meta_info.py
- mnelab/dialogs/montage.py
- mnelab/dialogs/plot_evoked.py
- mnelab/dialogs/reference.py
- mnelab/dialogs/run_ica.py
- mnelab/dialogs/xdf_chunks.py
- mnelab/dialogs/xdf_streams.py
- mnelab/io/xdf.py
- mnelab/mainwindow.py
- mnelab/test/test_readers.py
- mnelab/viz.py
- setup.cfg
I initially just wanted to add an `isort` key in `setup.cfg` to avoid defining the value in the VSCode settings, then figured we might as well ensure it in pre-commit. Of course this comes with cleaning up all imports at once to make the style checks green 😅
> Add isort pre-commit hook

- mnelab/model.py
Since #283 an array with 0 rows is used to represent no events (instead of None), so the if-condition in `Model.import_events` (line 232) needs to be based on length. Also, the event array has to be of dtype `int` ([ref](https://mne.tools/stable/glossary.html#term-events)).
> Fix event import

- mnelab/model.py
Fixes for two small issues:
- If the channel locations are included in the loaded file, the key "montage" in the data set dict is not set. As this is used to decide whether the montage details in the infowidget should be shown, they aren't.
- The `nchan` string includes "(X bad)" in case of bad channels.
> Improve infowidget montage entry

- CHANGELOG.md
- mnelab/dialogs/pick_channels.py
- mnelab/mainwindow.py
- mnelab/model.py
Example dialog:
The existing implementation of `pick_channels` converts the "pick" to a "drop". What was the reasoning there and should it be done in this case as well?
> Add ability to pick channels by channel type

- mnelab/dialogs/xdf_chunks.py
Since nothing can be changed it is better to show a "Close" button instead of "OK". Also, the first row is now automatically selected.
> Select first row and use Close in XDF chunks dialog

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/settings.py
It's rather minimal so far, but I'm sure people will think of things to add :D
I created a common interface for both the implicit (window size/pos, recent files) and the explicit (max_recent, ?) settings. "Reset to defaults" does however only reset what can be changed in the settings dialog. Should this be extended to the rest? And should toolbar and statusbar be toggleable from the settings dialog?
> Add a settings menu

- mnelab/dialogs/__init__.py
- mnelab/dialogs/drop_bad_epochs.py
- mnelab/mainwindow.py
- mnelab/model.py
This provides an interface for [mne.Epochs.drop_bad](https://mne.tools/stable/generated/mne.Epochs.html#mne.Epochs.drop_bad).
Example dialog:
Only available channel types are displayed, alternatively we could always show all but grey-out non-available ones?
> Add ability to drop bad epochs

- CHANGELOG.md
- mnelab/mainwindow.py
Previouly, export to .FIF.GZ exported to a file `<name>.gz.fif.gz`. For some reason, `QFileDialog` appends `.gz` when no extension is given in `<name>`.
This PR removes this extra `.gz` and correctly exports to `<name>.fif.gz`. Note that this means that it is impossible to export to a file named `<name>.gz.fif.gz`, but I think that's OK.
Fixes #300.
> Use correct extension for export to .fif.gz

- CHANGELOG.md
- mnelab/mainwindow.py
This PR disables (hides) the close window button in the overwrite dialog. It also makes sure that both the default button and pressing Escape is mapped to "Create new dataset" (so the current data is not accidentally overwritten).
> Improve overwrite dialog

- CHANGELOG.md
- mnelab/dialogs/calc.py
- mnelab/dialogs/erds.py
- mnelab/mainwindow.py
- mnelab/viz.py
To allow cancelling the significance mask calculation, this required more changes than expected...
The figures created by [`AverageTFR.plot`](https://mne.tools/stable/generated/mne.time_frequency.AverageTFR.html#mne.time_frequency.AverageTFR.plot) can't be pickled (and thus not passed between processes), so we can't just extend the existing `mnelab.viz.plot_erds` with significance masks and call it like it's done for ICA calculation. I've created a new function `calc_tfr_and_masks` which just calculates the tfr and significance masks in a new process. After that, `plot_erds` takes the return of `calc_tfr_and_masks` to create the figures.
Naming and data structure are of course up for discussion 😅
> Add significance masks to Plot ERDS maps

- CHANGELOG.md
- mnelab/io/writers.py
Rounding physical minima and maxima to integers avoids warnings when exporting to EDF. Since the data is converted to µV, integers are not a problem.
> Round pmin and pmax in EDF export

- CHANGELOG.md
- mnelab/dialogs/__init__.py
- mnelab/dialogs/mat.py
- mnelab/io/mat.py
- mnelab/io/readers.py
- mnelab/mainwindow.py
2D arrays from arbitrary MAT files can be loaded by selecting the variable and setting the sampling frequency in a dedicated dialog. Fixes #195.
> Add support for loading MAT files

- CHANGELOG.md
- mnelab/__init__.py
- mnelab/icons/mnelab-logo-macos.svg
- mnelab/icons/mnelab-logo.svg
This needs to be tested on Windows, macOS, and Linux. It might not be possible to make this 100% work without creating a standalone version (see https://doc.qt.io/qt-6/appicon.html), but maybe it can be good enough.
One minor thing I noticed is that when quitting MNELAB on macOS, the default Python rocket icon is briefly visible. But I guess that's not too bad.
> Add app icon

- CHANGELOG.md
- mnelab/dialogs/annotations.py
- mnelab/dialogs/epoch.py
- mnelab/dialogs/events.py
- mnelab/dialogs/utils.py
- mnelab/dialogs/xdf_streams.py
- mnelab/mainwindow.py
- mnelab/model.py
- mnelab/viz.py
This lets dialogs in which users can select events show the event label instead of the integer id. If events aren't generated from annotations, but imported from a file, no event mapping exists, so the ids are shown. A future PR could introduce the possibility to change the event mapping.
> Let event selection dialogs show event labels

- CHANGELOG.md
- mnelab/dialogs/find_events.py
- mnelab/mainwindow.py
- mnelab/model.py
This adds proper history for the Find Events dialog. The argument `consecutive` now also supports `"increasing"` (the default) in addition to `True` and `False`. Fixes #331.
> Add complete history for find_events

- CHANGELOG.md
- mnelab/model.py
Fixes #330. Depending on the actual length, this shows either h m s, m s, or just s.
> More readable signal lengths

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/model.py
This PR changes the current cursor to `Qt.WaitCursor`, effectively the "spinning wheel" mentioned in https://github.com/cbrnr/mnelab/issues/308, during a `data_changed` task. I went with `data_changed` because I thought it would be more impactful but maybe it's not the best place.
Here is how it looks for me:
https://user-images.githubusercontent.com/18143289/161078577-09984e53-1d41-42ae-b0f8-c220fc7e1ec3.mp4
Closes https://github.com/cbrnr/mnelab/issues/308
> ENH: wait_cursor

- .github/workflows/release.yml
- .github/workflows/test.yml
- CHANGELOG.md
- mnelab/io/xdf.py
Some marker streams have not been detected correctly, because we switched the nominal sampling rate to `float`, but still compared everything with strings (i.e. `'0.00000' == '0'`). This PR fixes this comparison by comparing numbers instead of strings.
> Fix XDF marker stream detection

- CHANGELOG.md
- mnelab/__init__.py
- mnelab/io/xdf.py
This now only requires marker streams to have a sampling rate different from zero. This means that regularly sampled marker streams are currently not supported, but unless these are of type string they will be regular channels anyway. Regularly sampled string channels do not work yet (and never have previously).
> Fix XDF marker streams

- CHANGELOG.md
- mnelab/dialogs/mat.py
- mnelab/io/mat.py
This adds the possibility to import 1D numeric arrays from .mat files. Therefore, arrays must be 1D or 2D and their dtypes must be either float or double. Fixes #347.
> Enable importing 1D arrays from .mat

- mnelab/io/xdf.py
The previous change related to importing XDF marker streams turned out to be too liberal. It required only a sampling rate of 0 Hz, but there are 0 Hz streams with multiple channels, which are problematic right now.
Therefore, this change defines marker streams that can be imported as annotations as follows:
- Irregular sampling rate (i.e. 0 Hz)
- Just one channel
The data type is irrelevant, so we can still import numeric markers as long as these two criteria are met.
> Restrict XDF markers to one channel

- CHANGELOG.md
- mnelab/mainwindow.py
- mnelab/widgets/__init__.py
- mnelab/widgets/infowidget.py
Supersedes #343 with a simpler approach using a `QStackedWidget`.
Closes #312.
To Do:
> Show shortcuts when no file is open

- CHANGELOG.md
- mnelab/io/readers.py
- mnelab/test/test_readers.py
Previously, trying to open an unsupported file type resulted in a cryptic error message ("TypeError: cannot unpack non-iterable NoneType object"). This PR changes it to a helpful message ("Unsupported file type.").
> Improve unsupported file type error message

- CHANGELOG.md
- mnelab/io/xdf.py
This PR adds "µV", "μV", and "uV" to the list of supported units (previously, only "microvolt" and "microvolts" were supported).
> Support more microvolt units in XDF

- README.md
- setup.cfg
Bump PySide6 (new key sequence types), MNE, and Matplotlib (breaking backend change) dependencies.
> Bump dependencies

- readthedocs.yml
This fixes a version conflict, which prevented the docs from building.
> Fix RTD by upgrading to latest image

- CHANGELOG.md
- mnelab/io/writers.py
This fixes a bug where EEG channels, which are represented in V internally, get scaled incorrectly when exporting to BrainVision.
> Correctly scale data when exporting to BV

- mnelab/io/writers.py
Exporting in µV increases compatibility with BrainVision Analyzer (which can handle V, but the default zoom level is not appropriate).
> Export to BV in µV

- CHANGELOG.md
- mnelab/__init__.py
- mnelab/mainwindow.py
- mnelab/utils/__init__.py
- mnelab/utils/utils.py
I'm using `QStyleHints.colorScheme()` here BTW, but the app is still listening for `QEvent.PaletteChange` (instead of `QStyleHints.colorSchemeChanged`), at least on macOS that's the only way it works.
Tested and works:
> Try simplified theme detection

- mnelab/__init__.py
This setting is deprecated, high DPI icons are now used by default.
> Remove `AA_UseHighDpiPixmaps` setting

- CHANGELOG.md
- mnelab/dialogs/xdf_streams.py
- mnelab/io/xdf.py
- mnelab/mainwindow.py
This PR adds the option to select a subset of marker streams. The previous behavior was to load all marker streams, which remains the default. However, a subset can now be selected by passing a list of marker stream IDs as the `marker_ids` argument.
> Select marker streams

- mnelab/mainwindow.py
Due to issues with mne-qt-browser messing up icon paths, I'm forcing the Matplotlib backend for now.
> Set MNE browser backend to Matplotlib

- CHANGELOG.md
- src/mnelab/mainwindow.py
It seems like overwriting `event()` does not propagate the correct event type anymore (Qt >= 6.7.0), so I'm switching to `eventFilter()`, which is probably more suitable anyway.
> Fix drag and drop

- src/mnelab/mainwindow.py
The icon theme is only set when the `PaletteChange` event is emitted, so we need to do this manually on init (otherwise, the default light icon theme will be used even in dark mode).
> Manually trigger `PaletteChange`

- CHANGELOG.md
- README.md
- docs/source/tutorial/index.md
- pyproject.toml
- src/mnelab/io/writers.py
- src/mnelab/utils/dependencies.py
In addition to just replacing pyedflib with edfio, this PR promotes edfio to a core dependency. The main rationale behind this decision is that edfio is pure Python, whereas pyedflib relies on a C library.
There is a drawback: it is now not possible to export to BDF. However, I think this is not a big deal, because BDF is a niche format, and users should prefer EDF in almost all cases.
> Replace pyedflib with edfio

- CHANGELOG.md
- src/mnelab/io/mat.py
- src/mnelab/io/npy.py
- src/mnelab/io/readers.py
- src/mnelab/io/xdf.py
- src/mnelab/mainwindow.py
This is the recommended and documented approach, which specifically means that we do not have to fiddle with the private `._filenames` attribute anymore.
This is what you meant, right @larsoner?
> Refactor readers to subclass `BaseRaw`

- CONTRIBUTING.md
- README.md
Using uv greatly simplifies installing and running MNELAB for both users and developers.
> More uv instructions

- src/mnelab/__init__.py
To avoid cluttering the stdout with Qt warning and debug messages, this PR disables them. Of course, this assumes that they are actually not important, but we can always enable them again if we ever encounter a Qt-related bug.
> Filter Qt warnings

- CHANGELOG.md
- src/mnelab/model.py
- tests/test_model.py
Fixes #130. Changes in model.py: def append_data(self, names) to correctly show the code history
> Show correct history for appending data

- pyproject.toml
Since picard does not depend on numexpr anymore, we can finally officially support Python 3.13.
> Bump picard

- .github/workflows/test.yml
- pyproject.toml
Since MNELAB has been compatible with 3.13 for some time, I think it was an oversight that our tests didn't include that version.
> Add tests on Python 3.13

- src/mnelab/dialogs/channel_stats.py
The Channel Stats dialog used a Close button that extended over the entire dialog width. Using a `QDialogButtonBox` ensures that the platform default layout is used.
> Use standard Close button

- pyproject.toml
This is the recommended way to add dev dependencies now (which replaces optional dependencies). Note that `uv sync` and `uv run` automatically install the dev dependency group.
> Add dev dependency group

- .github/workflows/test.yml
This helps catch more potential errors, as all tests should pass without warnings and errors.
> Run pytest with warnings as errors

- pyproject.toml
This should ensure `LICENSE` is included in the sdist built by `uv-build`.
Note that I have not tested this ;) 
Please see:
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files
> Add `license-files` entry to `pyproject.toml`

- CHANGELOG.md
- src/mnelab/__init__.py
- standalone/create-standalone-linux.sh
- standalone/create-standalone-windows.ps1
- standalone/mnelab-macos.spec
I think this is the required fix for the error that the Windows standalone version currently throws when trying to filter data:
```
Traceback (most recent call last):
File "joblib\parallel.py", line 1916, in _get_sequential_output
File "joblib\parallel.py", line 1608, in print_progress
File "joblib\parallel.py", line 1558, in _print
AttributeError: 'NoneType' object has no attribute 'write'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "mnelab\mainwindow.py", line 1135, in filter_data
self.model.filter(dialog.lower, dialog.upper, dialog.notch)
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "mnelab\model.py", line 38, in wrapper
result = f(self, *args, **kwargs)
File "mnelab\model.py", line 516, in filter …
```
> Redirect stdout/stderr for frozen Windows
